#!/usr/bin/env powershell
# Tron Nile Testnet Fix - Quick Start Guide

Write-Host @"
╔════════════════════════════════════════════════════════════╗
║  TRON NILE TESTNET DEPOSIT FIX - QUICK START               ║
╚════════════════════════════════════════════════════════════╝

PROBLEM DIAGNOSED:
  ✗ Backend configured for Tron MAINNET
  ✗ You deposited to Tron NILE TESTNET
  ✗ Token address mismatch → deposit not detected

SOLUTION APPLIED:
  ✓ Updated .env with Nile testnet configuration
  ✓ Updated RPC_TRON to https://nile.trongrid.io
  ✓ Updated TRON_USDT_ADDRESS to TF17BoRp2cDBi2hpdvKAhERMLCHRJ1NqFn
  ✓ Updated TRON_USDC_ADDRESS to TEkxiTehnzSmSe2XqrBj4w6WKHC3sSL7R7
  ✓ Created diagnostic and verification scripts

NEXT STEPS:
"@

Write-Host "`n1️⃣  Build the backend:"
Write-Host "   cd c:\Users\USER\Documents\builds\andes\backend"
Write-Host "   pnpm run build`n"

Write-Host "2️⃣  Start the backend:"
Write-Host "   node scripts/run-with-memory.js"
Write-Host "   (Or: node dist/index.js if MongoDB is running)`n"

Write-Host "3️⃣  Wait 30-60 seconds for blockchain listener to activate`n"

Write-Host "4️⃣  Run diagnostics in a NEW terminal:"
Write-Host "   cd c:\Users\USER\Documents\builds\andes\backend"
Write-Host "   pnpm tsx scripts/diagnose-deposits.ts`n"

Write-Host "5️⃣  Verify your deposit on explorer:"
Write-Host "   https://nile.tronscan.org"
Write-Host "   Search for your Tron address`n"

Write-Host @"
CONFIGURATION CHANGES MADE:

File: .env
  OLD: RPC_TRON="https://api.tronstack.io"
  NEW: RPC_TRON="https://nile.trongrid.io"

  OLD: TRON_USDT_ADDRESS=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t
  NEW: TRON_USDT_ADDRESS=TF17BoRp2cDBi2hpdvKAhERMLCHRJ1NqFn

  OLD: TRON_USDC_ADDRESS=TCFLL5dx5ZJdKnWuesXxi1VPwjLVmWZZy9
  NEW: TRON_USDC_ADDRESS=TEkxiTehnzSmSe2XqrBj4w6WKHC3sSL7R7

Also updated RPC endpoints for other networks:
  RPC_ETHEREUM → https://eth.llamarpc.com
  RPC_BSC → https://bsc.llamarpc.com
  RPC_POLYGON → https://polygon.llamarpc.com

NEW SCRIPTS CREATED:

1. scripts/diagnose-deposits.ts
   → Scans database for your deposits
   → Shows all users and addresses
   → Lists detected transactions

2. scripts/verify-nile-deposit.ts
   → Checks Tron Nile testnet for your transaction
   → Shows current configuration
   → Helps troubleshoot

3. scripts/update-nile-config.ts
   → Auto-updates .env for Nile (if needed)

EXPECTED BEHAVIOR AFTER FIX:

1. Backend starts and activates blockchain listener
2. Listener polls https://nile.trongrid.io for transfers
3. Your 10 USDT deposit is detected (token address now matches)
4. Deposit recorded in database with status "pending"
5. After 19 confirmations, status changes to "confirmed"
6. Your balance updates to show 10 USDT
7. Dashboard displays the deposit

TROUBLESHOOTING:

If deposit still not showing:
  1. Check logs: pnpm tsx scripts/diagnose-deposits.ts
  2. Verify TX on explorer: https://nile.tronscan.org
  3. Ensure backend is running and listener is active
  4. Confirm your address matches between backend and explorer
  5. Wait for 19 confirmations on Tron network

Blockchain Listener Status:
  - Should start automatically when backend runs
  - Polls every 30 seconds by default
  - Check console output for "Starting blockchain listener"
  - Look for "Detected transfer" logs

DATABASE SCHEMA:

Deposits table will show:
  {
    userId: "your_user_id",
    network: "tron",
    tokenSymbol: "USDT",
    tokenAddress: "TF17BoRp2cDBi2hpdvKAhERMLCHRJ1NqFn",
    amount: 10,
    status: "confirmed",
    confirmations: 19+,
    txHash: "your_transaction_hash",
    toAddress: "your_nile_address"
  }

QUESTIONS?

1. Verify you're sending to YOUR address (not wallet address)
   - Your address format: TR... or TF... (starts with T)
   - Different per user, generated by backend
   - Found in: GET /api/addresses/{userId}

2. Verify you're using Tron Nile testnet
   - Check transaction on https://nile.tronscan.org
   - NOT mainnet (https://tronscan.org)
   - NOT Shasta (https://shasta.tronscan.org)

3. Verify transaction status
   - Wait for at least 19 confirmations
   - Block time on Tron: ~3 seconds
   - 19 blocks ≈ 60 seconds

Good luck! Your deposit should appear within 1-2 minutes of backend restart. 🚀
"@
